# ------------------------------------------------------------------------
# MAKEFILE
#
# Created by   : mmphosis
#
# Purpose      : Makefile for gcc
#
# Compilers:
#
# gcc
#
# ------------------------------------------------------------------------

SRC=xpack
PRG=xpack
all: $(PRG)

$(PRG): $(SRC).c makefile
	gcc -DMINGW -o ..\$(PRG) $(SRC).c 
