# ------------------------------------------------------------------------
# MAKEFILE
#
# Created by   : mmphosis
#
# Purpose      : Makefile for gcc
#
# Compilers:
#
# gcc
#
# ------------------------------------------------------------------------

SRC=m2s
PRG=m2s
all: $(PRG)

$(PRG): $(SRC).c makefile
	gcc -DMINGW -o ../$(PRG) $(SRC).c 
