# ------------------------------------------------------------------------
# MAKEFILE
#
# Created by   : mmphosis
#
# Purpose      : Makefile for gcc
#
# Compilers:
#
# gcc
#
# ------------------------------------------------------------------------

SRC=a2fcbmp
PRG=a2b
all: $(PRG)

$(PRG): $(SRC).c makefile
	gcc -DMINGW -o ../$(PRG) $(SRC).c 
